version: '3'
# Named volumes
volumes:
  # MySQL Data
  laravel-api-mysql-data:
    driver: local
  # Redis Data
  laravel-api-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: laravel-api-mysql
    volumes:
      - laravel-api-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=laravel-api
      - MYSQL_DATABASE=laravel-api
      - MYSQL_USER=laravel-api
      - MYSQL_PASSWORD=laravel-api

  # Redis
  cache:
    image: redis:4.0
    container_name: laravel-api-redis
    command: --appendonly yes
    volumes:
      - laravel-api-redis-data:/data
    ports:
      - "6380:6379"

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: laravel-api-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"

  # Laravel Queues
  queue:
    image: ambientum/php:7.2
    container_name: laravel-api-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app